spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/INFLEARN_BACK?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: backend_developer
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
logging.level:
  org.hibernate.SQL: debug