spring:
  profiles:
    active: dev

  main:
    allow-bean-definition-overriding: true

  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 1000

jasypt:
  encryptor:
    password: ${JASYPT_PASSWORD:NONE}
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

logging:
  level:
    org.hibernate.SQL: INFO
    com.zaxxer.hikari: TRACE
    com.zaxxer.hikari.HikariConfig: DEBUG
