spring:
  profiles:
    active: dev

  h2:
    console:
      enabled: true

  main:
    allow-bean-definition-overriding: true

  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 1000

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(6/Ponyj/US/TvdVEZJfmcsPmvaXwKaeCWyudJyZDkNoTnloH+R4r0dR8MFFrA90SkJag3l4b67WQrIqR9Oz8Y6IK45M9ypW0DMxUGsOFc3rFijwDrAhK2Q==)
            client-secret: ENC(FoXXYeauW6EKov8iMfbE57X8cV9jEf4WSQ+FFmjnNIakgPv768fkng==)
            redirect-uri: '{baseUrl}/api/v1/login/oauth2/{registrationId}'
            scope: profile, email
          github:
            client-id: 6384cb2b837888daf770
            client-secret: 1314fab68e5fc4f3ef0f20b0cdd4581e30cd690c
            redirect-uri: '{baseUrl}/api/v1/login/oauth2/{registrationId}'
          facebook:
            client-id: 3986592298112371
            client-secret: 8e6b34d5dbad3f03c4c70ecd95661530
            scope: email, public_profile
            userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,name,email,verified
            redirect-uri: '{baseUrl}/api/v1/login/oauth2/{registrationId}'


logging:
  level:
    org.hibernate.SQL: info

jasypt:
  encryptor:
    password: ${JASYPT_PASSWORD:NONE}
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
