spring:
  profiles:
    active: dev

  main:
    allow-bean-definition-overriding: true

  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 1000

jasypt:
  encryptor:
    password: ${JASYPT_PASSWORD:NONE}
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

logging:
  level:
    web: DEBUG
    org.hibernate.SQL: INFO
    com.zaxxer.hikari: TRACE
    com.zaxxer.hikari.HikariConfig: DEBUG

slack:
  subscription-notification: ENC(dfdaw83QivKfAmHIN66q8jLzXiw+g54PmRv1TFEb0Zru0Ev/cZGxKln+L41bT5Ou7iTCyCK1kfUx9kF8jtmZUMOC+jxf+XBF1nmeIE0NtFwdLuGl9lijmgsmjrmZmc3j)
