spring:
  config:
    activate:
      on-profile: dev

  h2:
    console:
      enabled: true

  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create

decorator:
  datasource:
    p6spy:
      enable-logging: true
