spring:
  profiles:
    active: dev
    include: oauth

  main:
    allow-bean-definition-overriding: true

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 1000

logging:
  level:
    org.hibernate.SQL: info
---
spring:
  config:
    activate:
      on-profile: dev

  jpa:
    hibernate:
      ddl-auto: create

decorator:
  datasource:
    p6spy:
      enable-logging: true
---
spring:
  config:
    activate:
      on-profile: prod

  jpa:
    hibernate:
      ddl-auto: none

logging:
  level:
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari: TRACE

decorator:
  datasource:
    p6spy:
      enable-logging: false

jasypt:
  encryptor:
    bean: jasyptStringEncryptor