spring:
  config:
    activate:
      on-profile: prod

  jpa:
    hibernate:
      ddl-auto: validate

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ENC(XiSaJchRrKscl04MbWkITuRJSXNoSkUEdHwBexW/GC4=)
            client-secret: ENC(qJkGCzj826OgFis5FQxX+/+KsSkuwqmd9kFq7kSH3R8vXbO+DVagckoXIBBjQs0C7dYMswI08hY=)
            scope: user, email

decorator:
  datasource:
    p6spy:
      enable-logging: false
