name: gradle CD
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Set up AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: S3 upload
        run: aws deploy push --application-name team-ark-inflearn-back --description "team-ark-inflearn-back" --s3-location s3://team-ark/server/build.zip --source .

      - name: Code Deploy
        run: aws deploy create-deployment --application-name 	team-ark-inflearn-back --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name team-ark --s3-location bucket=team-ark,bundleType=zip,key=server/build.zip
